In [54]:
# Dependencies
import numpy as np
import pandas as pd

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [2]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [3]:
# Create our session (link) from Python to the DB
session = Session(engine)

In [6]:
Base.classes.keys()

['measurement', 'station']

## D1: Determine the Summary Statistics for June

In [57]:
# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract

# 2. Write a query that filters the Measurement table to retrieve the temperatures for the month of June. 
result_june = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date) == 6)

In [58]:
result_june

In [59]:
#  3. Convert the June temperatures to a list.
june_temp = []
for temp in result_june:
    june_temp.append(temp[1])

In [60]:
june_temp

[78.0,
 76.0,
 78.0,
 76.0,
 77.0,
 78.0,
 77.0,
 78.0,
 78.0,
 79.0,
 78.0,
 78.0,
 78.0,
 77.0,
 78.0,
 78.0,
 77.0,
 77.0,
 82.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 77.0,
 76.0,
 78.0,
 78.0,
 78.0,
 78.0,
 77.0,
 78.0,
 73.0,
 70.0,
 76.0,
 77.0,
 77.0,
 77.0,
 77.0,
 78.0,
 77.0,
 77.0,
 78.0,
 78.0,
 77.0,
 78.0,
 78.0,
 75.0,
 76.0,
 76.0,
 77.0,
 78.0,
 76.0,
 77.0,
 75.0,
 77.0,
 76.0,
 76.0,
 75.0,
 77.0,
 77.0,
 76.0,
 78.0,
 77.0,
 76.0,
 77.0,
 76.0,
 76.0,
 77.0,
 77.0,
 78.0,
 77.0,
 77.0,
 77.0,
 76.0,
 75.0,
 76.0,
 76.0,
 77.0,
 76.0,
 73.0,
 73.0,
 75.0,
 77.0,
 76.0,
 77.0,
 79.0,
 78.0,
 79.0,
 78.0,
 78.0,
 79.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 78.0,
 77.0,
 76.0,
 78.0,
 78.0,
 77.0,
 78.0,
 78.0,
 73.0,
 76.0,
 77.0,
 75.0,
 76.0,
 74.0,
 75.0,
 77.0,
 76.0,
 77.0,
 78.0,
 79.0,
 77.0,
 78.0,
 79.0,
 78.0,
 78.0,
 78.0,
 78.0,
 79.0,
 79.0,
 82.0,
 80.0,
 79.0,
 79.0,
 78.0,
 78.0,
 77.0,
 78.0,
 78.0,
 73.0,
 75.0,
 75.0,
 76.0,
 84.0,
 79.0,
 76.0,
 79.0,
 79.0,
 77.0,
 79.0,
 78.0,
 78.0,
 79.0,
 77.0,
 79.0,
 78.0,
 78.0,
 78.0,
 79.0,
 77.0,
 78.0,
 78.0,
 78.0,
 78.0,
 79.0,
 79.0,
 77.0,
 78.0,
 78.0,
 78.0,
 79.0,
 79.0,
 77.0,
 79.0,
 79.0,
 79.0,
 81.0,
 76.0,
 80.0,
 78.0,
 76.0,
 71.0,
 71.0,
 74.0,
 76.0,
 78.0,
 77.0,
 77.0,
 73.0,
 77.0,
 78.0,
 78.0,
 80.0,
 79.0,
 78.0,
 77.0,
 76.0,
 77.0,
 77.0,
 78.0,
 80.0,
 79.0,
 79.0,
 77.0,
 78.0,
 79.0,
 80.0,
 76.0,
 79.0,
 80.0,
 79.0,
 79.0,
 79.0,
 79.0,
 80.0,
 79.0,
 79.0,
 80.0,
 80.0,
 77.0,
 79.0,
 83.0,
 80.0,
 80.0,
 78.0,
 79.0,
 80.0,
 77.0,
 80.0,
 78.0,
 79.0,
 80.0,
 78.0,
 80.0,
 80.0,
 81.0,
 80.0,
 79.0,
 79.0,
 75.0,
 74.0,
 76.0,
 75.0,
 75.0,
 74.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 83.0,
 75.0,
 76.0,
 73.0,
 74.0,
 74.0,
 75.0,
 70.0,
 74.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 74.0,
 72.0,
 76.0,
 73.0,
 75.0,
 76.0,
 74.0,
 75.0,
 71.0,
 69.0,
 69.0,
 74.0,
 71.0,
 74.0,
 74.0,
 75.0,
 73.0,
 73.0,
 73.0,
 75.0,
 75.0,
 74.0,
 74.0,
 75.0,
 74.0,
 73.0,
 72.0,
 74.0,
 72.0,
 75.0,
 76.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 71.0,
 71.0,
 75.0,
 72.0,
 72.0,
 73.0,
 73.0,
 73.0,
 74.0,
 73.0,
 72.0,
 72.0,
 70.0,
 72.0,
 72.0,
 72.0,
 74.0,
 73.0,
 73.0,
 70.0,
 73.0,
 72.0,
 73.0,
 69.0,
 72.0,
 71.0,
 71.0,
 73.0,
 73.0,
 72.0,
 75.0,
 75.0,
 75.0,
 75.0,
 74.0,
 74.0,
 74.0,
 75.0,
 75.0,
 74.0,
 75.0,
 75.0,
 74.0,
 72.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 72.0,
 70.0,
 75.0,
 74.0,
 71.0,
 71.0,
 70.0,
 73.0,
 71.0,
 71.0,
 77.0,
 77.0,
 74.0,
 73.0,
 75.0,
 75.0,
 74.0,
 74.0,
 75.0,
 75.0,
 72.0,
 74.0,
 76.0,
 76.0,
 75.0,
 75.0,
 74.0,
 72.0,
 74.0,
 75.0,
 70.0,
 71.0,
 72.0,
 71.0,
 73.0,
 74.0,
 72.0,
 74.0,
 76.0,
 72.0,
 75.0,
 75.0,
 72.0,
 70.0,
 76.0,
 78.0,
 72.0,
 74.0,
 74.0,
 72.0,
 71.0,
 79.0,
 79.0,
 76.0,
 75.0,
 72.0,
 74.0,
 76.0,
 76.0,
 77.0,
 75.0,
 76.0,
 75.0,
 75.0,
 76.0,
 76.0,
 74.0,
 70.0,
 69.0,
 70.0,
 68.0,
 70.0,
 74.0,
 75.0,
 74.0,
 71.0,
 73.0,
 75.0,
 74.0,
 76.0,
 76.0,
 76.0,
 76.0,
 75.0,
 75.0,
 75.0,
 74.0,
 73.0,
 76.0,
 74.0,
 78.0,
 71.0,
 75.0,
 75.0,
 74.0,
 77.0,
 77.0,
 76.0,
 76.0,
 76.0,
 78.0,
 76.0,
 75.0,
 75.0,
 76.0,
 78.0,
 75.0,
 73.0,
 76.0,
 76.0,
 76.0,
 77.0,
 76.0,
 77.0,
 72.0,
 77.0,
 75.0,
 82.0,
 77.0,
 76.0,
 74.0,
 73.0,
 77.0,
 77.0,
 77.0,
 76.0,
 74.0,
 73.0,
 72.0,
 74.0,
 73.0,
 72.0,
 75.0,
 74.0,
 75.0,
 73.0,
 75.0,
 76.0,
 74.0,
 74.0,
 73.0,
 73.0,
 76.0,
 75.0,
 70.0,
 75.0,
 73.0,
 74.0,
 74.0,
 74.0,
 74.0,
 70.0,
 75.0,
 74.0,
 73.0,
 74.0,
 72.0,
 73.0,
 67.0,
 69.0,
 76.0,
 73.0,
 70.0,
 72.0,
 74.0,
 72.0,
 72.0,
 75.0,
 73.0,
 73.0,
 72.0,
 74.0,
 76.0,
 72.0,
 74.0,
 70.0,
 74.0,
 74.0,
 74.0,
 71.0,
 75.0,
 75.0,
 76.0,
 77.0,
 75.0,
 74.0,
 75.0,
 76.0,
 78.0,
 78.0,
 76.0,
 78.0,
 76.0,
 76.0,
 78.0,
 79.0,
 77.0,
 76.0,
 77.0,
 77.0,
 76.0,
 78.0,
 76.0,
 76.0,
 77.0,
 71.0,
 74.0,
 72.0,
 77.0,
 77.0,
 78.0,
 77.0,
 77.0,
 76.0,
 75.0,
 79.0,
 75.0,
 73.0,
 76.0,
 78.0,
 77.0,
 78.0,
 76.0,
 75.0,
 76.0,
 77.0,
 74.0,
 78.0,
 77.0,
 77.0,
 74.0,
 74.0,
 78.0,
 79.0,
 79.0,
 78.0,
 75.0,
 76.0,
 78.0,
 78.0,
 74.0,
 78.0,
 77.0,
 76.0,
 78.0,
 78.0,
 78.0,
 78.0,
 74.0,
 79.0,
 77.0,
 73.0,
 79.0,
 79.0,
 78.0,
 77.0,
 78.0,
 78.0,
 80.0,
 80.0,
 79.0,
 74.0,
 71.0,
 74.0,
 75.0,
 75.0,
 74.0,
 76.0,
 75.0,
 77.0,
 77.0,
 79.0,
 79.0,
 78.0,
 79.0,
 73.0,
 78.0,
 79.0,
 80.0,
 76.0,
 79.0,
 79.0,
 77.0,
 80.0,
 79.0,
 78.0,
 78.0,
 79.0,
 78.0,
 81.0,
 78.0,
 80.0,
 79.0,
 81.0,
 80.0,
 81.0,
 79.0,
 81.0,
 78.0,
 79.0,
 79.0,
 75.0,
 79.0,
 78.0,
 80.0,
 78.0,
 77.0,
 78.0,
 79.0,
 76.0,
 80.0,
 76.0,
 81.0,
 77.0,
 76.0,
 77.0,
 75.0,
 76.0,
 79.0,
 79.0,
 77.0,
 76.0,
 77.0,
 76.0,
 73.0,
 76.0,
 77.0,
 77.0,
 78.0,
 77.0,
 76.0,
 78.0,
 78.0,
 75.0,
 77.0,
 65.0,
 76.0,
 74.0,
 76.0,
 76.0,
 77.0,
 77.0,
 76.0,
 77.0,
 76.0,
 77.0,
 74.0,
 76.0,
 73.0,
 75.0,
 76.0,
 75.0,
 76.0,
 75.0,
 74.0,
 74.0,
 74.0,
 74.0,
 76.0,
 76.0,
 77.0,
 77.0,
 78.0,
 73.0,
 75.0,
 72.0,
 76.0,
 76.0,
 73.0,
 74.0,
 72.0,
 76.0,
 76.0,
 76.0,
 78.0,
 78.0,
 78.0,
 78.0,
 75.0,
 77.0,
 73.0,
 78.0,
 75.0,
 73.0,
 77.0,
 80.0,
 70.0,
 78.0,
 72.0,
 78.0,
 72.0,
 78.0,
 77.0,
 79.0,
 77.0,
 78.0,
 74.0,
 79.0,
 79.0,
 79.0,
 79.0,
 77.0,
 79.0,
 78.0,
 80.0,
 81.0,
 81.0,
 78.0,
 77.0,
 78.0,
 79.0,
 77.0,
 79.0,
 80.0,
 79.0,
 78.0,
 79.0,
 79.0,
 79.0,
 81.0,
 64.0,
 65.0,
 75.0,
 76.0,
 78.0,
 77.0,
 75.0,
 78.0,
 81.0,
 78.0,
 76.0,
 73.0,
 74.0,
 76.0,
 78.0,
 79.0,
 78.0,
 72.0,
 78.0,
 80.0,
 81.0,
 79.0,
 78.0,
 80.0,
 80.0,
 78.0,
 80.0,
 81.0,
 78.0,
 77.0,
 78.0,
 78.0,
 77.0,
 76.0,
 81.0,
 76.0,
 82.0,
 80.0,
 80.0,
 79.0,
 74.0,
 69.0,
 70.0,
 67.0,
 70.0,
 73.0,
 73.0,
 72.0,
 72.0,
 77.0,
 70.0,
 78.0,
 73.0,
 75.0,
 70.0,
 74.0,
 77.0,
 69.0,
 73.0,
 73.0,
 74.0,
 73.0,
 72.0,
 75.0,
 73.0,
 76.0,
 74.0,
 76.0,
 73.0,
 76.0,
 76.0,
 78.0,
 75.0,
 77.0,
 75.0,
 73.0,
 76.0,
 71.0,
 71.0,
 76.0,
 76.0,
 76.0,
 73.0,
 78.0,
 77.0,
 77.0,
 77.0,
 78.0,
 78.0,
 76.0,
 76.0,
 79.0,
 74.0,
 75.0,
 76.0,
 75.0,
 73.0,
 76.0,
 78.0,
 76.0,
 79.0,
 77.0,
 76.0,
 74.0,
 75.0,
 76.0,
 76.0,
 76.0,
 79.0,
 76.0,
 72.0,
 71.0,
 72.0,
 76.0,
 74.0,
 75.0,
 76.0,
 77.0,
 76.0,
 75.0,
 76.0,
 76.0,
 76.0,
 75.0,
 76.0,
 76.0,
 79.0,
 74.0,
 73.0,
 75.0,
 74.0,
 75.0,
 76.0,
 72.0,
 74.0,
 74.0,
 75.0,
 75.0,
 74.0,
 75.0,
 77.0,
 75.0,
 74.0,
 75.0,
 74.0,
 75.0,
 73.0,
 75.0,
 76.0,
 76.0,
 76.0,
 79.0,
 74.0,
 78.0,
 80.0,
 75.0,
 72.0,
 72.0,
 74.0,
 78.0,
 76.0,
 77.0,
 72.0,
 72.0,
 73.0,
 75.0,
 79.0,
 81.0,
 76.0,
 76.0,
 77.0,
 78.0,
 79.0,
 79.0,
 75.0,
 79.0,
 79.0,
 75.0,
 77.0,
 81.0,
 76.0,
 75.0,
 78.0,
 81.0,
 76.0,
 76.0,
 76.0,
 72.0,
 73.0,
 74.0,
 74.0,
 75.0,
 73.0,
 73.0,
 76.0,
 73.0,
 79.0,
 78.0,
 76.0,
 76.0,
 76.0,
 77.0,
 79.0,
 80.0,
 78.0,
 76.0,
 78.0,
 78.0,
 77.0,
 79.0,
 79.0,
 75.0,
 76.0,
 77.0,
 74.0,
 77.0,
 76.0,
 76.0,
 75.0,
 74.0,
 79.0,
 76.0,
 74.0,
 76.0,
 77.0,
 78.0,
 77.0,
 75.0,
 75.0,
 80.0,
 77.0,
 77.0,
 77.0,
 80.0,
 76.0,
 ...]

In [61]:
# 4. Create a DataFrame from the list of temperatures for the month of June. 
df_june_temp = pd.DataFrame(june_temp)
df_june_temp.head()

      0
0  78.0
1  76.0
2  78.0
3  76.0
4  77.0

In [62]:
# 5. Calculate and print out the summary statistics for the June temperature DataFrame.
df_june_temp.describe()

                 0
count  1700.000000
mean     74.944118
std       3.257417
min      64.000000
25%      73.000000
50%      75.000000
75%      77.000000
max      85.000000

## D2: Determine the Summary Statistics for December

In [63]:
# 6. Write a query that filters the Measurement table to retrieve the temperatures for the month of December.
result_dec = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date) == 12)

In [64]:
# 7. Convert the December temperatures to a list.
dec_temp = []
for temp in result_dec:
    dec_temp.append(temp[1])

In [66]:
# 8. Create a DataFrame from the list of temperatures for the month of December. 
df_dec_temp = pd.DataFrame(dec_temp)
df_dec_temp

         0
0     76.0
1     74.0
2     74.0
3     64.0
4     64.0
...    ...
1512  71.0
1513  71.0
1514  69.0
1515  65.0
1516  65.0

[1517 rows x 1 columns]

In [67]:
# 9. Calculate and print out the summary statistics for the Decemeber temperature DataFrame.
df_dec_temp.describe()

                 0
count  1517.000000
mean     71.041529
std       3.745920
min      56.000000
25%      69.000000
50%      71.000000
75%      74.000000
max      83.000000